title:               Matthew Spencer
description:         ""

baseurl:             ""
url:                 "https://matthewspencer.github.io"
permalink:           /:title/

markdown:            kramdown

exclude:
  - bin
  - README.md
  - LICENSE
  - package.json
  - node_modules
  - bower.json
  - bower_components
  - gulpfile.js
