title:       Matthew Spencer
description: ""

baseurl:     ""
url:         "https://transitory.technology"
permalink:   /:title/

markdown:    kramdown

exclude:
  - README.md
  - LICENSE
  - package.json
  - node_modules

sass:
  style: compressed
